config/routes.rb
StatTracker::Application.routes.draw do
  
  
  match 'index' => 'home#index', :as => 'home#index'
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  
  match 'compare' => 'home#compare', :as => 'home#compare'
  match 'franchise_compare' => 'home#franchise_compare'
  match 'home/google' => 'search#google_images', :as => 'home#google'
  match 'batting_leaderboards' => 'home#batting_leaderboard'
  match 'pitching_leaderboards' => 'home#pitching_leaderboard'
  match 'fielding_leaderboards' => 'home#fielding_leaderboard'
  match 'batting_leaders' => 'home#batting_leaders'
  match 'pitching_leaders' => 'home#pitching_leaders'
  match 'fielding_leaders' => 'home#fielding_leaders'
  match 'years_players' => 'home#years_players'
  match 'compare_players' => 'home#compare_players'
  
  match 'years_franchises' => 'home#years_franchises'
  match 'compare_franchises' => 'home#compare_franchises'

  match 'players/letter/' => 'players#by_letter', :as => :players_by_letter
  match 'players/letter/:letter' => 'players#letter', :as => :players_letter

  match 'players/position/' => 'players#by_position', :as => :players_by_position
  match 'players/position/:position' => 'players#position', :as => :players_position
  
  get 'home/autocomplete_player_name'
  get 'home/autocomplete_franchise_name'
  get 'players/autocomplete_player_name'
  get 'franchises/autocomplete_franchise_name'

  resources :teams

  resources :players

  resources :pitching_stats

  resources :pitching_post_stats

  resources :franchises

  resources :leagues

  resources :fielding_stats

  resources :fielding_post_stats

  resources :divisions

  resources :batting_stats

  resources :batting_post_stats
  
  match 'leaders/season/batting/:stat' => 'batting_stats#single_season'
  match 'leaders/season/batting_post/:stat' => 'batting_post_stats#single_season'
  match 'leaders/season/pitching/:stat' => 'pitching_stats#single_season'
  match 'leaders/season/pitching_post/:stat' => 'pitching_post_stats#single_season'
  match 'leaders/season/fielding/:stat' => 'fielding_stats#single_season'
  match 'leaders/season/fielding_post/:stat' => 'fielding_post_stats#single_season'
  
  match 'leaders/career/batting/:stat' => 'batting_stats#career'
  match 'leaders/career/batting_post/:stat' => 'batting_post_stats#career'
  match 'leaders/career/pitching/:stat' => 'pitching_stats#career'
  match 'leaders/career/pitching_post/:stat' => 'pitching_post_stats#career'
  match 'leaders/career/fielding/:stat' => 'fielding_stats#career'
  match 'leaders/career/fielding_post/:stat' => 'fielding_post_stats#career'

  match 'leaders/active/batting/:stat' => 'batting_stats#active'
  match 'leaders/active/batting_post/:stat' => 'batting_post_stats#active'
  match 'leaders/active/pitching/:stat' => 'pitching_stats#active'
  match 'leaders/active/pitching_post/:stat' => 'pitching_post_stats#active'
  match 'leaders/active/fielding/:stat' => 'fielding_stats#active'
  match 'leaders/active/fielding_post/:stat' => 'fielding_post_stats#active'
  
  match 'compare/season/batting/*comp' => 'batting_stats#season_compare'
  match 'compare/career/batting/*comp' => 'batting_stats#career_compare'
  match 'compare/multi/batting/*comp' => 'batting_stats#multi_compare'
  match 'compare/season/pitching/*comp' => 'pitching_stats#season_compare'
  match 'compare/career/pitching/*comp' => 'pitching_stats#career_compare'
  match 'compare/multi/pitching/*comp' => 'pitching_stats#multi_compare'

  match 'franchise_compare/season/*comp' => 'teams#season_compare'
  match 'franchise_compare/career/*comp' => 'teams#career_compare'
  match 'franchise_compare/multi/*comp' => 'teams#multi_compare'
  
  match 'seasonfinder/batting' => 'batting_stats#season_finder'
  match 'seasonfinder/batting/results' => 'batting_stats#find_seasons'
  match 'seasonfinder/pitching' => 'pitching_stats#season_finder'
  match 'seasonfinder/pitching/results' => 'pitching_stats#find_seasons'
  match 'seasonfinder/fielding' => 'fielding_stats#season_finder'
  match 'seasonfinder/fielding/results' => 'fielding_stats#find_seasons'
  
  match 'change_career_chart_batting' => 'batting_stats#change_career_chart'
  match 'change_career_table_batting' => 'batting_stats#change_career_table'
  match 'change_career_chart_pitching' => 'pitching_stats#change_career_chart'
  match 'change_career_table_pitching' => 'pitching_stats#change_career_table'
  match 'change_career_chart_team' => 'teams#change_career_chart'
  match 'change_career_table_team' => 'teams#change_career_table'
  
  match 'change_multi_chart_batting' => 'batting_stats#change_multi_chart'
  match 'change_multi_table_batting' => 'batting_stats#change_multi_table'
  match 'change_multi_chart_pitching' => 'pitching_stats#change_multi_chart'
  match 'change_multi_table_pitching' => 'pitching_stats#change_multi_table'
  match 'change_multi_chart_team' => 'teams#change_multi_chart'
  match 'change_multi_table_team' => 'teams#change_multi_table'
  
  match 'search' => 'home#search', :as => :search

  match 'team_search' => 'franchises#team_search', :as => :team_search
  match 'player_search' => 'players#player_search', :as => :player_search

   root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
autocomplete :player, :name, :display_value => :auto_search, :full => true
autocomplete :franchise, :name, :display_value => :auto_search, :full => true

  def index
  end

  def search
    @query = params[:query]
	puts @query.length
	if @query.length < 3
		flash[:notice] = 'Please be more specific with your search'
		redirect_to :back
	 end
    @players = Player.player_search(@query)
    @franchises = Franchise.team_search(@query)
    @total_hits = @players.size + @franchises.size
    if @total_hits == 1
      if @players.first != nil
        redirect_to @players.first
      end
      if @franchises.first != nil
        redirect_to @franchises.first
      end
    end
    
  end
  
  def batting_leaders
	stat = params[:stat].downcase.gsub(" ", "_")
	type = params[:type]
	post =  params[:post]
	if post.nil?
		redirect_to '/leaders/' + type + '/batting/' + stat
	else redirect_to '/leaders/' + type + '/batting_post/' + stat
	end
  end
  
  def pitching_leaders
	stat = params[:stat].downcase.gsub(" ", "_")
	type = params[:type]
	post =  params[:post]
	if post.nil?
		redirect_to '/leaders/' + type + '/pitching/' + stat
	else redirect_to '/leaders/' + type + '/pitching_post/' + stat
	end
  end

    def fielding_leaders
		stat = params[:stat].downcase.gsub(" ", "_")
		type = params[:type]
		post =  params[:post]
		if post.nil?
			redirect_to '/leaders/' + type + '/fielding/' + stat
		else redirect_to '/leaders/' + type + '/fielding_post/' + stat
		end
	end
  
  def years_players
	@comp = params[:comp]
	@players = params[:players]
	@player = []
	@player_ids = []
	@players.each { |p|
		if p != ""
			first_name, last_name, year, dash = p.split(" ")
			if !last_name.nil?
				last_name.chomp!(",")
				if Rails.env.development?
					@player.push(Player.find(:all, :select => [:id], :conditions => ["first_name = ? AND last_name = ? AND strftime('%Y', debut) = ?", first_name, last_name, year]))
				elsif Rails.env.production?
					@player.push(Player.find(:all, :select => [:id], :conditions => ["first_name = ? AND last_name = ? AND date_part('year', debut)::integer= ?", first_name, last_name, year.to_i]))
				else
					@player.push("")
				end
			end
		end
	}
	@player.each { |p|
		if p[0].nil?
		else
			id = p[0].id.to_s
			@player_ids.push(id)
		end
	}
	@years_array = []
	@player_ids.each { |p|
		@year = []
		@years = []
		if p[0].nil?		
		else
			@year = BattingStat.find(:all, :select => [:team_id], :conditions => ['player_id =?', p])
		end
		@year.each { |y|
			if @years.index(y.year).nil?
				@years.push(y.year)
			else
			end
		}
		@years_array.push(@years)
	}
	@type = params[:type]
	render :partial => 'years_players'
  end
  
  def compare_players
	@years = params[:years]
	@comp = params[:comp]
	@type = params[:type]
	@players = params[:players]
	if @players.nil?
		flash[:notice] = "Please enter a valid player's name using the autocomplete"
		redirect_to :back
	else
		if @type == 'career'
			string = "/" + @players.join('/')
			redirect_to '/compare/career/' + @comp + string
		elsif @type == 'season'
			new = []
			i = 0
			@players.each { |p|
				new.push(p + "." + @years[i])
				i += 1
			}
			string = "/" + new.join("/")
			redirect_to '/compare/season/' + @comp + string
		else 
			new = []
			i = 0
			@players.each { |p|
				new.push(p + "." + @years[i] + ':' + @years[i+1])
				i += 2
			}
			string = '/' + new.join('/')
			redirect_to '/compare/multi/' + @comp + string
		end
	end
  end
  
  def compare
  end
  
  def franchise_compare
  end
  
  def years_franchises
	@franchises = params[:franchises]
	@franchise= []
	@franchise_ids = []
	@franchises.each { |f|
		@franchise.push(Franchise.find(:all, :select => [:id], :conditions => ['name = ?', f]))
	}
	@franchise.each { |f|
		if f[0].nil?
		else
			id = f[0].id.to_s
			@franchise_ids.push(id)
		end
	}
	@years_array = []
	@franchise_ids.each { |f|
		@year = []
		@years = []
		if !f[0].nil?
			@year = Team.find(:all, :select => [:year], :conditions => ['franchise_id =?', f])
		end
		@year.each { |y|
			@years.push(y.year)
		}
		@years_array.push(@years)
	}
	@type = params[:type]
	render :partial => 'years_franchises'
  end
  
  def compare_franchises
	@years = params[:years]
	@type = params[:type]
	@franchises = params[:franchises]
	if @franchises.nil?
		flash[:notice] = "Please enter a valid team's name using the autocomplete"
		redirect_to :back
	else
		if @type == 'career'
			string = @franchises.join('/')
			redirect_to '/franchise_compare/career/' + string
		elsif @type == 'season'
			new = []
			i = 0
			@franchises.each { |p|
				new.push(p + "." + @years[i])
				i += 1
			}
			string = new.join("/")
			redirect_to '/franchise_compare/season/' + string
		else 
			new = []
			i = 0
			@franchises.each { |p|
				new.push(p + "." + @years[i] + ':' + @years[i+1])
				i += 2
			}
			string = new.join('/')
			redirect_to '/franchise_compare/multi/' + string
		end
	end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_years_franchises.js.erb
<%= form_tag compare_franchises_path(:type => @type, :franchises => @franchise_ids) do %>
			<% if @type == 'multi' or @type == 'season' %>
				<% for year in @years_array %>
	
						<%= select_tag 'years[]', options_for_select(year), :class => 'years_select' %>
						<% if @type == 'multi' %>
							to
							<%= select_tag 'years[]', options_for_select(year), :class => 'years_select'  %>
						<% end %>
						<br/>
				<% end %>
			<% end %>
		<br/>
		<%= submit_tag 'Compare' %>
	<% end %>
		

app/views/home/_years_players.js.erb
<%= form_tag compare_players_path(:comp => @comp, :type => @type, :players => @player_ids) do %>

			<% if @type == 'multi' || @type == 'season' %>
				<% for year in @years_array %>
				
						<%= select_tag 'years[]', options_for_select(year), :class => 'years_select' %>
						<% if @type == 'multi' %>
							to
							<%= select_tag 'years[]', options_for_select(year), :class => 'years_select' %>
						<% end %>
						<br/>
				<% end %>
			<% end %>
			<br/>
		<%= submit_tag 'Compare' %>
	<% end %>
		

app/views/home/about.html.erb
<h1>About</h1>

<p>	
StatTracker offers comparison and analysis tools for baseball fans.
</p>

<p>
StatTracker was developed by Andrew Caniglia, Chris Lebowitz, Christine Zhao, Won Ku Kim, Amy Tsai, and Sean Kung as part of their Information Systems software development course in Spring 2011.  
</p>

<p>
For more information about the Carnegie Mellon Information Systems program, visit the <a href="http://www.cmu.edu/information-systems">Information Systems Website</a>.
</p>

<!-- any page thats shorter than 100% height -->
<style>
#container{
margin-bottom:-110px;
}
</style>

app/views/home/batting_leaderboard.html.erb
<h1> Batting Leaderboards </h1>
 
<table>
<tr>
<td> 
<%= form_tag (batting_leaders_path) do %>
		<%= select_tag "stat", 
		raw("<option>Games</option>
		<option>Plate Appearances</option>
		<option>At Bats</option>
		<option>Runs</option>
		<option>Hits</option>
		<option>Doubles</option>
		<option>Triples</option>
		<option>Home Runs</option>
		<option>Total Bases</option>
		<option>Extra Base Hits</option>
		<option>RBI</option>
		<option>Stolen Bases</option>
		<option>Caught Stealing</option>
		<option>Walks</option>
		<option>Strikeouts</option>
		<option>Intentional Walks</option>
		<option>Hit By Pitch</option>
		<option>Sacrifice Hits</option>
		<option>Sacrifice Flies</option>
		<option>Grounded Into Double Plays</option>
		<option>Batting Average</option>
		<option>On Base Percentage</option>
		<option>Slugging Percentage</option>
		<option>On Base Plus Slugging</options>") %>
</td>
<td>
		<%= radio_button_tag 'type', 'season', true %>Season
		<%= radio_button_tag 'type', 'career' %>Career
		<%= radio_button_tag 'type', 'active' %>Active
</td>
<td>
		<%= submit_tag 'Submit' %>
</td>
</tr>
<tr>
<td></td>
<td><%= check_box_tag 'post', 'post', false %>Postseason</td>
</tr>
</table>
	<% end %>
	
		<style>
#container{
margin-bottom:-110px;
}
</style>
	

app/views/home/compare.html.erb
<%title 'Compare Players'%>



	<%= form_tag years_players_path, :remote => true, :id => 'years' do %>
		<div id = "comp">			
			Batting<%= radio_button_tag 'comp', 'batting', true %>
			Pitching<%= radio_button_tag 'comp', 'pitching' %>
		</div>
		<br/>
		<table>
		<tr>
		<td>
		<div id = "players">
			<table>
				<div id = 'text1'><%= text_field_tag 'players[]', '', :size => 32, :id => "player1", :placeholder => "Start typing a player's name...", :autocomplete => home_autocomplete_player_name_path%></div>
				<div id = 'text2'><%= text_field_tag 'players[]', '', :size => 32, :id => "player2", :autocomplete => home_autocomplete_player_name_path%></div>
				<div id = 'text3'><%= text_field_tag 'players[]', '', :size => 32, :id => "player3", :autocomplete => home_autocomplete_player_name_path%></div>
				<div id = 'text4'><%= text_field_tag 'players[]', '', :size => 32, :id => "player4", :autocomplete => home_autocomplete_player_name_path%></div>
				<div id = 'text5'><%= text_field_tag 'players[]', '', :size => 32, :id => "player5", :autocomplete => home_autocomplete_player_name_path%></div>
			</table>
		</div>
			<br/>
                        Career<%= radio_button_tag 'type', 'career' %>
			<br/>
			Season<%= radio_button_tag 'type', 'season' %>
			<br/>
			Multi-Year<%= radio_button_tag 'type', 'multi' %>
			<br/>
			<br/>
			<%#= submit_tag 'Compare'%>
		</td>
	<% end %>	

		<td class = 'years' >
			<div id = 'years_place'>
			</div>
		</td>
	</tr>
</table>
<script type="text/javascript">
  $('input[name="type"]').change(function(){
    $(this).parents('form:first').submit();
  });
  $('input[name="comp"]').change(function(){
    if ($('input[name="type"]:checked').val() != null)
      $('input[name="type"]').parents('form:first').submit();
  });
  $('input[name="players[]"]').live('keyup focusout', function(){
    if ($('input[name="type"]:checked').val() != null)
      $('input[name="type"]:first').parents('form:first').submit();
  });
  
  
</script>

app/views/home/compare2.html.erb
	<table>
	
		<tr>
			<td>
				&nbsp;
			</td>
			
			<td>
				<ul style="width:auto;">
					<% form_tag(search_path) do %>
                	<%= text_field_tag('query') %>               
                	<% end %>
                </ul></li>
            </td>
         </tr>   
         
		<tr>
			<td>
				&nbsp;
			</td>
						
			
			<td>
				<ul style="width:auto;">
					<% form_tag(search_path) do %>
                	<%= text_field_tag('query') %>               
                	<% end %>
                </ul></li>
            </td>
            
			<td>										
				<input type="radio" id = "radio1" onclick="
					if(this.checked == '0') 
					{
						document.getElementById('textbox1').style.display='none'; //hide textbox
						document.getElementById('radio2').style.display='none'; //hide checkbox

					} 
					else 
					{
						document.getElementById('textbox1').style.display='block'; //show textbox
						document.getElementById('radio2').style.display='block'; //show checkbox
					}
					return true;">Add More			
			</td>
            
            <td>
            	<ul style="width:auto;">
            		<%= submit_tag('Compare') %>
            	</ul></li>
            </td>            
         </tr>  
         					
		<tr>							

			<td>
				<input type="text" id="textbox1" style="display:none">				
			</td>
			
			<td>	
				<input type="radio"  style="display:none" id = "radio2" onclick="
					if(this.checked == '0') 
					{
						document.getElementById('textbox2').style.display='none'; //hide textbox
					} 
					else 
					{
						document.getElementById('radio3').style.display='block'; //hide textbox
						document.getElementById('textbox2').style.display='block'; //show textbox
					}
					return true;">
				
			</td>
			
		</tr>
		
		<tr>
			
			<td>
				<input type="text" id="textbox2"  style="display:none">				
			</td>		
		
			<td>	
				<input type="radio"  style="display:none" id = "radio3" onclick="
					if(this.checked == '0') 
					{
						document.getElementById('textbox3').style.display='none'; //hide textbox
					} 
					else 
					{
						document.getElementById('radio3').style.display='block'; //hide textbox
						document.getElementById('textbox3').style.display='block'; //show textbox
					}
					return true;">					
				
			</td>					
		</tr>
		
		<tr>
			<td>
				<input type="text" id="textbox3"  style="display:none">				
			</td>	
		</tr>

		
		<% form_tag (
		
		
	
		
		

		

app/views/home/fielding_leaderboard.html.erb
<h1> Fielding Leaderboards </h1>
 
<table>
<tr>
<td> 
<%= form_tag (fielding_leaders_path) do %>
		<%= select_tag "stat", 
		raw("<option>Games</option>
		<option>Games Started</option>
		<option>Chances</option>
		<option>Put Outs</option>
		<option>Assists</option>
		<option>Errors Made</option>
		<option>Double Plays</option>
		<option>Passed Balls</option>
		<option>Wild Pitches</option>
		<option>Stolen Bases</option>
		<option>Caught Stealing</option>")
		%>
</td>
<td>
		<%= radio_button_tag 'type', 'season' , true%>Season
		<%= radio_button_tag 'type', 'career' %>Career
		<%= radio_button_tag 'type', 'active' %>Active
</td>
<td>
		<%= submit_tag 'Submit' %>
</td>
</tr>
<tr>
<td></td>
<td><%= check_box_tag 'post', 'post', false %>Postseason</td>
</tr>
</table>
	<% end %>
		<style>
#container{
margin-bottom:-110px;
}
</style>

app/views/home/franchise_compare.html.erb
<%title 'Franchise Comparison'%>
	<%= form_tag years_franchises_path, :remote => true, :id => 'years' do %>
		<table>
		<tr>
		<td>
		<div id = "franchises">
			<table>
				<div id = 'text1'><%= text_field_tag 'franchises[]', '', :size => 32, :placeholder => "Start typing a team's name...", :autocomplete => home_autocomplete_franchise_name_path%></div>
				<div id = 'text2'><%= text_field_tag 'franchises[]', '', :size => 32, :autocomplete => home_autocomplete_franchise_name_path%></div>
				<div id = 'text3'><%= text_field_tag 'franchises[]', '', :size => 32, :autocomplete => home_autocomplete_franchise_name_path%></div>
				<div id = 'text4'><%= text_field_tag 'franchises[]', '', :size => 32, :autocomplete => home_autocomplete_franchise_name_path%></div>
				<div id = 'text5'><%= text_field_tag 'franchises[]', '', :size => 32, :autocomplete => home_autocomplete_franchise_name_path%></div>
			</table>
		</div>
                        <br/>
			Franchise<%= radio_button_tag 'type', 'career' %>
			<br/>
			Season<%= radio_button_tag 'type', 'season' %>
			<br/>
			Multi-Year<%= radio_button_tag 'type', 'multi' %>
			<br/>
			<br/>
			<%#= submit_tag 'Compare' %>
		</td>
	<% end %>	

		<td class = 'years' >
			<div id = 'years_place'>
			</div>	
		</td>
	</tr>
</table>
<script type="text/javascript">
  $('input[name="type"]').change(function(){
    $(this).parents('form:first').submit();
  });
  $('input[name="franchises[]"]').live('keyup focusout', function(){
    if ($('input[name="type"]:checked').val() != null)
      $('input[name="type"]').parents('form:first').submit();
  });
</script>

app/views/home/index.html.erb
<script type="text/javascript">
	$(window).load(function() {
    $('#slider').nivoSlider( {
	effect:'fade',
		directionNav:true, // Next & Prev navigation
    directionNavHide:true, // Only show on hover
    controlNav:true
	}	);
	});
	</script>
<div id="slider">
    <img src="../images/slide1.jpg" alt="" />
    <img src="../images/slide2.jpg" alt="" />
	<img src="../images/slide3.jpg" alt="" />
	 <img src="../images/slide4.jpg" alt="" />
	  <img src="../images/slide5.jpg" alt="" />
	   <img src="../images/slide6.jpg" alt="" />
	    <img src="../images/slide7.jpg" alt="" />
		 <img src="../images/slide9.jpg" alt="" />
		  <img src="../images/slide8.jpg" alt="" />
		   <img src="../images/slide10.jpg" alt="" />
		    <img src="../images/slide11.jpg" alt="" />
			<img src="../images/slide12.jpg" alt="" />
		
</div>

<div class="nivo-directionNav" style="display:none; ">
	<a class="nivo-prevNav">Prev</a>
	<a class="nivo-nextNav">Next</a>
	
	
</div>


	<div class="button" id="comparePlayers"><%= link_to 'Compare Players now > ', 'compare' %></div>
        <div class="button" id="compareTeams"><%= link_to 'Compare Teams now > ', 'franchise_compare' %></div>

	


	
	
	
	

app/views/home/pitching_leaderboard.html.erb
<h1> Pitching Leaderboards</h1>

<table>
<tr>
<td>
	<%= form_tag (pitching_leaders_path) do %>
			<%= select_tag "stat", 
			raw("<option>Games</option>
			<option>Win Loss Percentage</option>
			<option>Innings Pitched</option>
			<option>ERA</option>
			<option>Opponents Batting Average</option>
			<option>Walks and Hits Innings Pitched</option>
			<option>Hits per 9 Innings</option>
			<option>Home Runs per 9 Innings</option>
			<option>Walks per 9 Innings</option>
			<option>Strikeouts per 9 Innings</option>
			<option>Strikeouts per Walk</option>
			<option>Wins</option>
			<option>Losses</option>
			<option>Games Started</option>
			<option>Complete Games</option>
			<option>Shutouts</option>
			<option>Saves</option>
			<option>Hits</option>
			<option>Earned Runs</option>
			<option>Home Runs</option>
			<option>Walks</option>
			<option>Strikeouts</option>
			<option>Intentional Walks</option>
			<option>Wild Pitches</option>
			<option>Hit By Pitch</option>
			<option>Balks</option>
			<option>Batters Faced</option>
			<option>Games Finished</option>
			<option>Runs</option>
			")
			%>
</td>
<td>
		<%= radio_button_tag 'type', 'season', true %>Season
		<%= radio_button_tag 'type', 'career' %>Career
		<%= radio_button_tag 'type', 'active' %>Active
</td>
<td>
		<%= submit_tag 'Submit' %>
</td>
</tr>
<tr>
<td></td>
<td><%= check_box_tag 'post', 'post', false %>Postseason</td>
</tr>
</table>
	<% end %>
	
		<style>
#container{
margin-bottom:-110px;
}
</style>
	

app/views/home/players.js.erb
$("players").update("<%= escape_javascript(render(:partial => "players")) %>");

app/views/home/search.html.erb
<h1> Search Result </h1>
<% if @players.empty? & @franchises.empty? %>
<br />
<h2>No players / teams found</h2>
<% end %>

<p class="supertiny">&nbsp;</p>

<% unless @players.empty? %>
	<p><em><strong>Players matching term '<%= @query %>'</strong></em></p>
	<ul>
            <table class="datagrid">
              <thead class="datagrid">
                  <th width="250">Name</th>
                  <th width="250">Active</th>
                  <th>Play Year</th>
              </thead>
              <% for player in @players do %>

              <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
                  <td align ="center"><%= link_to player.name, player_path(player) %></td>
                  <td align ="center">
                      <% if player.final_game.nil? %>
                          <strong></strong>&#10004
                      <% end %>
                      <% if !player.final_game.nil? %>
                          <strong></strong>&#10008
                      <% end %>
                  </td>
                  <td align ="center">
                      <% if player.final_game.nil? %>
                          <%= player.debut.strftime("%Y") %> -
                      <% end %>
                      <% if !player.final_game.nil? %>
                          <%= player.debut.strftime("%Y") %> - <%= player.final_game.strftime("%Y") %>
                      <% end %>
                  </td>
              </tr>
            <% end %>
            </table>
	</ul>
	<p class="smtext">&nbsp;</p>
<% end %>

<% unless @franchises.empty? %>
	<p><em><strong>Teams matching term '<%= @query %>'</strong></em></p>
	<ul>
            <table class="datagrid">
              <thead class="datagrid">
                  <th width="250">Name</th>
                  <th width="250">Active</th>
                  <th>Year</th>
              </thead>
              <% for franchise in @franchises do %>
              <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
                  <td align ="center"><%= link_to franchise.name, franchise_path(franchise) %></td>
                  <td align ="center">
                      <% if franchise.active %>
                          <strong></strong>&#10004
                      <% end %>
                      <% if !franchise.active %>
                          <strong></strong>&#10008
                      <% end %>
                  </td>
                  <td align ="center">
                      <%=  "#{franchise.teams.first.year}" %>-<%=  "#{franchise.teams.last.year}" if !franchise.active? %>
                  </td>
              </tr>
            <% end %>
            </table>
	</ul>
	<p class="smtext">&nbsp;</p>
<% end %>

	<style>
#container{
margin-bottom:-110px;
}
</style>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
    
    <p> This is still under construction. However, by using this site, you agree: 
    </p>
    
    <ol>
 		<li>To use StatTracker for individual use and not for any illegal activities.</li>
		<li>To not breakdown the site.</li>
	</ol>
 
<h3>Modifications to Service</h3>

<p>StatTracker reserves the right at any time to modify or discontinue, temporarily or permanently, this web site with or without notice. You agree that StatTracker shall not be liable to you or to any third party for any modification, suspension or discontinuance of the web site.</p>

<style>
#container{
margin-bottom:-110px;
}
</style>

app/views/home/years.js.erb
$("years").update("<%= escape_javascript(render(:partial => "years")) %>");